### ISSUE TITLE
ssn_deleg_amt field maps's contents is never read

### ISSUE THREAD

**Issue by anton-trunov** [Zilliqa/staking-contract#101]
Commit b710edc8b0676e0ea40dc5422d7d2f8c8e1552b4

The `ssn_deleg_amt` field map is only updated (including deletion of its keys).

**Comment by bb111189** [comment]
It is more for wallet developers.

**Comment by anton-trunov** [comment]
I see, then maybe we could document this and close the issue.

**Comment by renlulu** [comment]
@anton-trunov I will just close this so that we can more focus on other issues, thanks!
