### ISSUE TITLE
Admin transitions should validate if commission rate is within limits

### ISSUE THREAD

**Issue by anton-trunov** [Zilliqa/staking-contract#115]
Admin can make a typo too! The following transitions don't validate the `comm` parameter and just record it in `ssnlist`.
- `AddSSNAfterUpgrade` 
- `AddSSN`

**Comment by bb111189** [comment]
Similar audit issue: https://github.com/Zilliqa/staking-contract/issues/136
Fix: https://github.com/Zilliqa/staking-contract/pull/134
