### ISSUE TITLE
6.6 Misleading Names

### ISSUE THREAD

**Issue by renlulu** [Zilliqa/staking-contract#131]
Some functions and variables have misleading names. This greatly decreases the code readability. Examples are:
1. The argument `proxyContract` in `multisig_wallet.scilla` must be a `gZIL` token contract.The name of the argument sounds list the proxy contract must be passed as an argument. This is a confusing name that can lead to human errors.

```
transition SubmitCustomChangeMinterTransaction (proxyContract : ByStr20, new_minter : ByStr20)
transaction = ChangeMinter new_minter;
SubmitCustomTransaction proxyContract transaction
end
```

2. Procedure `ReDelegStakeAmt`  in ` ssnlist.scilla`. The Re prefix usually means "again" or "repeat". But this procedure actually removes the delegate stake.

3. `HasRewardToWithdraw` and `HasBufferedDeposit` procedures in `ssnlist.scilla`. Both procedures are effectively doing assertions and return no values. Meanwhile the "Has-" prefixed functions are expected to return bool value. In addition, both procedures throw errors when condition is actually satisfied. E.g. `HasRewardToWithdraw` throws error when exists some available reward for a given SSN and delegator.

**Comment by renlulu** [comment]
I think suggestion 2 and 3 are strong, and would like to rename it to `UnDelegateStakeAmt`, `AssertNoRewards` and `AssertNoBufferedDeposit`. 

In terms of suggestion 1, I remember we had a internal discussion previous, and decided not to change even it was confusing? @bb111189 @AmritKumar

**Comment by AmritKumar** [comment]
1. I propose changing `proxyContract`to `CalleeContract`. It makes it generic enough. And we add a comment for each transition saying that for this transition, `CalleeContract` is the proxy contract. Similarly for the the gZIL contract, we say `CalleeContract` is the gZILToken contract.
2. Yes, let's change it to `UnDelegateStakeAmt`.
3. Yes, let's change it to `AssertNoRewards`and `AsseertNoBufferedDeposit`.
