### ISSUE TITLE
6.10 Transition AddSSN Does Not Validate the Commission

### ISSUE THREAD

**Issue by renlulu** [Zilliqa/staking-contract#136]
The commission for a newly created SSN is not validated in the AddSSN transition. Meanwhile the transition UnpdateComm perform a check on the new commission. Even though the AddSSN is admin only function, lack of validation can lead to an invalid state of the contract.

**Comment by renlulu** [comment]
I personally think we will ask ssn operator's opinion for their init commission, and we should take care of the value when we execute `AddSSN`. Would like to hear from you @AmritKumar @bb111189

**Comment by AmritKumar** [comment]
Yes, let's take their suggestion and add the checks on commission rate.
