### ISSUE TITLE
Stake rewards if lower than mindelegate cannot be staked back

### ISSUE THREAD

**Issue by AmritKumar** [Zilliqa/staking-contract#169]
**Problem:**

1. The rationale behind putting a `MinDelegateAmount` was to ensure that it is meaningful to pay the gas to withdraw the reward earned at the end of each cycle.

2. A high value of `MinDelegateAmount` ensures that the reward earned per cycle (even when a considerable supply is staked leading to a reduced yield) is high enough for users to pay for the gas and earn a net positive number of ZILs.

3. However, when the reward earned has to be staked back, it must also be larger than `MinDelegateAmount` otherwise the contract may prevent users from staking back their reward.

4. The above point means that the value of `MinDelegateAmount` should not be too high to prevent staking of rewards.

In essence, there is a fine balance between the two aspects, one requiring `MinDelegateAmount` to be high enough to provide meaningful return and the other requiring `MinDelegateAmount` to be low enough for users to be able to stake their rewards back.

**Solutions:**

**Solution 1:** A possible fix to this dilemma is to have a check in the `Delegate` transition to check for already existing delegators. If a delegator already has enough stake at a given SSN, then any new amount delegated to it does not need to meet the `MinDelegateAmount` criteria. This will also be helpful with the situations where, a delegator already has enough stake with an SSN but wants to add some more to his stake, but this additional stake is lower than `MinDelegateAmount`

**Solution 2:** A simpler solution will be to set the value of `MinDelegateAmount` that balances the constraints on both sides.

**Comment by bb111189** [comment]
We will go for `MinDelegateAmount` at 10 ZIL
