### ISSUE TITLE
ZILLIQA STAKING rewards

### ISSUE THREAD

**Issue by etrolik** [Zilliqa/staking-contract#214]
Hi @renlulu @hicaru, Trying to figure out why there is a delay in assigning staking rewards from Zillacracy. It seems to be happening on multiple ocassions so not sure if a correct amount of ZIL rewards was assigned to my wallet. I have checked and last rewards were sent on 12-Jan-2021 15:42, Statistics updated on: Jan-13-2021 17:19:46 and i still don't see anything in my wallet (UNCLAIMED ZIL REWARDS). From what I can see I get rewards every couple days would that be correct?. I see blocks # and rewards but I dont see date against these blocks so hard to say how often I should be looking for these.  zil16add4q2nld0m3fee0eef4lqj6agc33g7hkhgyj

**Comment by renlulu** [comment]
hmmm but i can see your rewards though, could you please refresh your page?

![image](https://user-images.githubusercontent.com/8149051/104433520-26a1fa80-55c5-11eb-928f-2bf36670f078.png)

**Comment by etrolik** [comment]
Hmm I keep refreshing logging back and forth with my ledger and still notihing- See the attached.

**Comment by etrolik** [comment]
> @renlulu Hmm I keep refreshing logging back and forth with my ledger and still notihing- See the attached.
> ![image](https://user-images.githubusercontent.com/72214527/104445064-f3e20d00-5598-11eb-8033-89bc1a410ad3.png)

now I can see it after the new block round
