### ISSUE TITLE
QSP-5 Gas Usage / for Loop Concerns

### ISSUE THREAD

**Issue by renlulu** [Zilliqa/staking-contract#26]
Description: Gas usage is a main concern for smart contract developers and users, since high gas costs may prevent users from wanting to use the smart contract. Even worse, some gas usage issues may prevent the contract from providing services entirely. For example, if a for loop requires too much gas to exit, then it may prevent the contract from functioning correctly entirely. It is best to break such loops into individual functions as possible.

Recommendation: Instead of rewarding all SSNs all at once, reward them in batches of a given size (passed in as parameter).

**Comment by bb111189** [comment]
We will add a constant with max number of ssn set to 20
