### ISSUE TITLE
Rename SSNList's contract parameters to be prefixed with init_

### ISSUE THREAD

**Issue by anton-trunov** [Zilliqa/staking-contract#76]
My suggestion would be to rename
-  `proxy_address` to `init_proxy_address`,
- `gzil_address` to `init_gzil_address`.

This will make the contract more robust to future changes against issues like the one covered by PR https://github.com/Zilliqa/staking-contract/pull/75.

This suggestion also make the style of the proxy contract and the SSNList contract more uniform.

**Comment by bb111189** [comment]
https://github.com/Zilliqa/staking-contract/pull/108

**Comment by bb111189** [comment]
merged to dev
