### ISSUE TITLE
Easy to switch admin to a non-functional one

### ISSUE THREAD

**Issue by anton-trunov** [Zilliqa/staking-contract#78]
Both Proxy and SSNList contracts (`UpdateAdmin` transitions) allow one to switch
their admins to a non-functional one as their is no confirmation that the
ownership receiving side will be able to actually perform any actions.

A possible solution to this issue could be to switch admins in stages, following
a protocol like the following one:
1. The *current* admin asks to switch to a new admin, making the contract state to
   remember that it's in the process of changing admins, but the current one is
   still active.
2. The *new* admin calls `UpdateAdmin` (with their own address as `admin`
   parameter) thereby confirming that it is active and can take ownership.
3. If the *new* admin is inactive or the original admin has changed their mind,
   then the original admin calls `UpdateAdmin` again and restores their
   ownership.

**Comment by bb111189** [comment]
This is a good idea @renlulu

**Comment by renlulu** [comment]
How about we have two transition:

```
transition UpdateAdmin(admin: ByStr20, initiator: ByStr20)
  IsProxy;
  IsAdmin initiator;
  contractstagingadmin := admin
end

transition ConfirmAdmin(initiator: ByStr20)
  IsProxy;
  IsStagingAdmin initiator;
  contractadmin := initiator;
end


```
