### ISSUE TITLE
Ssn's ActiveStatus field is redundant

### ISSUE THREAD

**Issue by anton-trunov** [Zilliqa/staking-contract#97]
Commit b710edc8b0676e0ea40dc5422d7d2f8c8e1552b4.

The `ActiveStatus` field of `Ssn` datatype is redundant since there is an invariant that `ActiveStatus = (Minstake < StakeAmount)` meaning that we can easily compute `ActiveStatus` on the fly.

**Comment by anton-trunov** [comment]
Here is a train of thought that backs up the reasoning above.

Let’s suppose the admin calls `UpdateStakingParameters` transition and changes `minstake` to a new value.
If the new value of `minstake` is lower than before, more SSNs can become *active* with their status `false` in the `ssnlist` field map. And vice versa, some SSNs may become inactive if `minstake` is increased, but their statuses won’t automatically change to reflect that.

**Comment by bb111189** [comment]
It is easier for web application and verifer to query the contract state `ActiveStatus` and display it on the frontend. In this case, there is no need for web app to manually calculate it on the fly. So I think we can retain the existing setup.
