### ISSUE TITLE
Hard to understand `1 zil` comment

### ISSUE THREAD

**Issue by anton-trunov** [Zilliqa/staking-contract#99]
Commit b710edc8b0676e0ea40dc5422d7d2f8c8e1552b4

I don't understand what `1 zil` means in the following snippet:

```
field minstake: Uint128 = Uint128 0
(* 1 zil *)
field mindelegstake: Uint128 = Uint128 0
```

**Comment by renlulu** [comment]
We don't have this any more in the newer version lol

**Comment by renlulu** [comment]
Also I will close this to make more space for other issues! @anton-trunov
